
- name: "Copy configs to {{ cassandra_config }} and {{ cassandra_env }}"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: root
    group: root
    mode: '0664'
# https://docs.ansible.com/ansible/latest/modules/template_module.html 
# http://www.filepermissions.com/file-permissions-index
  with_items:
   - { src: "cassandra.yaml.j2", dest: "{{cassandra_config}}" }
   - { src: "cassandra-env.sh.j2", dest: "{{cassandra_env}}" }
  notify: Restart cassandra

- meta: flush_handlers

- name: "Download cassandra.yml from remote to ansible host"
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
    flat: yes
  with_items:
   - { src: "{{cassandra_config}}", dest: ./files/ }
   - { src: "{{cassandra_env}}", dest: ./files/ }
# https://docs.ansible.com/ansible/latest/modules/fetch_module.html