- name: "Create {{ cassandra_path_for_setup }} if it does not exist"
  file:
    path: "{{ cassandra_path_for_setup }}"
    recurse: yes
    owner: root 
    group: root 
    mode: '0755'
    state: directory  # directory or file
# https://docs.ansible.com/ansible/latest/modules/file_module.html
# http://www.filepermissions.com/file-permissions-index

- name: "Copy cql files to {{ cassandra_path_for_setup }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0664'
# https://docs.ansible.com/ansible/latest/modules/template_module.html 
# http://www.filepermissions.com/file-permissions-index 
  with_items:
    - {src: "create_monitor_user.cql.j2", dest: "{{ cassandra_path_for_setup }}/create_monitor_user.cql" }
    - {src: "set_tracing_on.cql.j2", dest: "{{ cassandra_path_for_setup}}/set_tracing_on.cql" }
    - {src: "check_role.cql.j2", dest: "{{ cassandra_path_for_setup}}/check_role.cql" }
    - {src: "check_tracing.cql.j2", dest: "{{ cassandra_path_for_setup}}/check_tracing.cql" }

- name: "Check if tracing is enabled"
  shell: cqlsh -f {{ cassandra_path_for_setup }}/check_tracing.cql -u {{ cassandra_default_user }} -p {{ cassandra_default_password }} | sed 's|\.||g' | awk '{print $4}'
  register: cassandra_tracing_status
# https://docs.ansible.com/ansible/latest/modules/shell_module.html#shell-module 

- name: "Enable tracing if it is disabled"
  shell: cqlsh -f {{ cassandra_path_for_setup }}/set_tracing_on.cql -u {{ cassandra_default_user }} -p {{ cassandra_default_password }} | sed 's|\.||g' | awk '{print $4}'
  when: cassandra_tracing_status['stdout'] == "disabled"
  register: output

- debug:
    var: "output"
# https://docs.ansible.com/ansible/latest/modules/debug_module.html 