- name: "Download files from remote to ansible host"
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
    flat: yes
  with_items:
   - { src: "{{cassandra_config}}", dest: ./files/cassandra.yaml }
# https://docs.ansible.com/ansible/latest/modules/fetch_module.html