---
# handlers file for centos_apache_cassandra
- name: "Set tracing probability"
  shell: "nodetool settraceprobability {{ cassandra_tracing_probability }}"


- name: "Create monitoring user"
  shell: "nodetool settraceprobability {{ cassandra_tracing_probability }}"