---
# handlers file for centos_apache_cassandra
- name: "Set tracing probability"
  shell: "nodetool settraceprobability {{ cassandra_tracing_probability }}"


- name: "Create monitoring user"
  shell: cqlsh -f {{ cassandra_path_for_setup}}/creawte_monitor_user.cql -u {{ cassandra_default_user }} -p {{ cassandra_default_password }}